// examples/shiftboard/frontend/src/lib/components/LoginScreen.svelte
<script lang="ts">
  import { enhance } from '$app/forms';

  // Action failure data from the ?/login form action (+page.server.ts).
  let { form }: { form?: { error?: string; email?: string } | null } = $props();

  let busy = $state(false);
</script>

<div class="login-screen">
  <!-- Server-side login: posts to the ?/login form action, which calls
       POST /auth/{repo}/login and stores the tokens in httpOnly cookies.
       Works without JavaScript; use:enhance just adds the busy state. -->
  <form
    class="login-card"
    method="POST"
    action="?/login"
    use:enhance={() => {
      busy = true;
      return async ({ update }) => {
        await update();
        busy = false;
      };
    }}
  >
    <h1>Shiftboard</h1>
    <p class="login-hint">Weekend shift planning, with an AI planner on the side.</p>

    <label>
      Email
      <!-- Prefilled demo credentials (created by examples/shiftboard/setup.mjs). -->
      <input
        type="email"
        name="email"
        value={form?.email ?? 'planner@example.com'}
        autocomplete="username"
        required
      />
    </label>
    <label>
      Password
      <input
        type="password"
        name="password"
        value="Planner12345!"
        autocomplete="current-password"
        required
      />
    </label>

    {#if form?.error}
      <p class="login-error" role="alert">{form.error}</p>
    {/if}

    <button type="submit" disabled={busy}>
      {busy ? 'Signing in…' : 'Sign in'}
    </button>
  </form>
</div>

// examples/vue-board/src/components/LoginScreen.vue
<script setup lang="ts">
/**
 * Login form bound to useAuth().login (client.loginWithEmail under the
 * hood: HTTP login + WebSocket connect + JWT auth in one call).
 * Demo credentials are prefilled.
 */
import { ref } from 'vue';
import type { UseAuthReturn } from '@raisindb/client/vue';
import { REPOSITORY } from '../lib/raisin';

const props = defineProps<{ auth: UseAuthReturn }>();

const email = ref('planner@example.com');
const password = ref('Planner12345!');
const error = ref<string | null>(null);
const submitting = ref(false);

async function submit() {
  if (submitting.value) return;
  error.value = null;
  submitting.value = true;
  try {
    await props.auth.login(email.value.trim(), password.value, REPOSITORY);
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err);
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <div class="login-screen">
    <form class="login-card" @submit.prevent="submit">
      <h1>Vue Board</h1>
      <p class="login-hint">
        RaisinDB Vue composables demo — sign in with the prefilled demo
        account (<code>planner@example.com</code>).
      </p>
      <label>
        Email
        <input v-model="email" type="email" name="email" autocomplete="username" required />
      </label>
      <label>
        Password
        <input v-model="password" type="password" name="password" autocomplete="current-password" required />
      </label>
      <p v-if="error" class="login-error" role="alert">{{ error }}</p>
      <button type="submit" :disabled="submitting || auth.isLoading.value">
        {{ submitting ? 'Signing in…' : 'Sign in' }}
      </button>
    </form>
  </div>
</template>
