// examples/taskpilot/app/components/ChatPanel.tsx
/**
 * The live chat column: message bubbles, streaming text, tool-call badges,
 * error banner, input. Bound to the shared useConversation return.
 */
import { useEffect, useRef, useState, type KeyboardEvent } from 'react';
import type { UseConversationReturn } from '@raisindb/client/react';

export function ChatPanel({ chat }: { chat: UseConversationReturn }) {
  const [input, setInput] = useState('');
  const scroller = useRef<HTMLDivElement | null>(null);

  // Only user/assistant messages with text render as bubbles; tool/system
  // messages surface via the tool-call badges, and plan/task lifecycle
  // messages (messageType ai_plan / ai_task_update) belong to the plan
  // panel, not the transcript.
  const visibleMessages = chat.messages.filter(
    (m) =>
      (m.role === 'user' || m.role === 'assistant') &&
      m.content &&
      m.messageType !== 'ai_plan' &&
      m.messageType !== 'ai_task_update',
  );

  // NOTE: isWaiting must NOT feed this indicator — the store sets
  // isWaiting=true at end-of-turn ("waiting for user input"), so including
  // it shows a permanent "thinking…" bubble after every reply.
  const thinking =
    chat.isStreaming && !chat.streamingText && chat.activeToolCalls.length === 0;

  // Keep the chat scrolled to the bottom as messages/stream/tools change.
  useEffect(() => {
    scroller.current?.scrollTo({ top: scroller.current.scrollHeight });
  }, [visibleMessages.length, chat.streamingText, chat.activeToolCalls.length]);

  function send() {
    const text = input.trim();
    if (!text || chat.isStreaming) return;
    setInput('');
    chat.sendMessage(text).catch((err) => {
      console.warn('[chat] send failed:', err);
    });
  }

  function onKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }

  return (
    <section className="panel chat-panel" data-testid="chat">
      <h2 className="panel-title">Pilot</h2>
      <div className="chat-messages" ref={scroller} data-testid="chat-messages">
        {visibleMessages.length === 0 && !chat.isStreaming && (
          <p className="muted chat-empty">
            Ask Pilot for a plan — e.g. “Plan and execute: mark ‘Design hero
            section’ as done, then summarize the checklist.”
          </p>
        )}

        {visibleMessages.map((message, i) => (
          <div
            key={message.id ?? `${message.role}-${i}`}
            className={`bubble ${message.role}`}
            data-testid={`bubble-${message.role}`}
          >
            {message.content}
          </div>
        ))}

        {chat.isStreaming && chat.streamingText && (
          <div className="bubble assistant streaming" data-testid="streaming">
            {chat.streamingText}
          </div>
        )}

        {chat.activeToolCalls.length > 0 && (
          <div className="tool-calls">
            {chat.activeToolCalls.map((tool) => (
              <span
                key={tool.id}
                className={`tool-badge ${tool.status}`}
                data-testid="tool-badge"
              >
                🔧 {tool.functionName}
                {tool.status === 'running' ? (
                  <span className="spinner" />
                ) : tool.status === 'completed' ? (
                  ' ✓'
                ) : (
                  ' ✗'
                )}
              </span>
            ))}
          </div>
        )}

        {thinking && <div className="bubble assistant thinking">thinking…</div>}
      </div>

      {chat.error && (
        <p className="error-banner" role="alert" data-testid="chat-error">
          {chat.error}
        </p>
      )}

      <div className="chat-input">
        <input
          type="text"
          placeholder="Message Pilot…"
          data-testid="chat-input"
          value={input}
          disabled={chat.isStreaming}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={onKeyDown}
        />
        <button
          data-testid="chat-send"
          disabled={chat.isStreaming || !input.trim()}
          onClick={send}
        >
          Send
        </button>
      </div>
    </section>
  );
}

// examples/shiftboard/frontend/src/lib/components/ChatPanel.svelte
<script lang="ts">
  import type { AgentChatState } from '../stores/chat.svelte';

  let {
    chat,
    title = 'Planning chat',
    placeholder = 'Message the agent…',
    emptyHint = 'Ask the agent anything.',
    testid = 'chat',
  }: {
    chat: AgentChatState;
    title?: string;
    placeholder?: string;
    emptyHint?: string;
    testid?: string;
  } = $props();

  let input = $state('');
  let scroller = $state<HTMLElement>();

  // Only user/assistant messages with text are rendered as bubbles;
  // tool/system messages are surfaced via the tool-call badges instead.
  // Plan/task lifecycle messages (messageType ai_plan / ai_task_update —
  // their content is just the plan/task title) belong to the plan panel,
  // not the transcript.
  const visibleMessages = $derived(
    chat.snapshot.messages.filter(
      (m) =>
        (m.role === 'user' || m.role === 'assistant') &&
        m.content &&
        m.messageType !== 'ai_plan' &&
        m.messageType !== 'ai_task_update',
    ),
  );

  const thinking = $derived(
    chat.snapshot.isStreaming &&
      !chat.snapshot.streamingText &&
      chat.snapshot.activeToolCalls.length === 0,
  );

  // Keep the chat scrolled to the bottom as messages/stream/tool calls change.
  $effect(() => {
    void visibleMessages.length;
    void chat.snapshot.streamingText;
    void chat.snapshot.activeToolCalls.length;
    scroller?.scrollTo({ top: scroller.scrollHeight });
  });

  function send() {
    const text = input.trim();
    if (!text || chat.snapshot.isStreaming) return;
    input = '';
    chat.send(text);
  }

  function onKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }
</script>

<section class="panel chat-panel" data-testid={testid}>
  <h2 class="panel-title">{title}</h2>

  <div class="chat-messages" bind:this={scroller}>
    <!-- SSR already renders the history below; only show the placeholder
         when there is nothing to show yet. -->
    {#if !chat.ready && visibleMessages.length === 0}
      <p class="muted">Opening conversation…</p>
    {:else if chat.ready && visibleMessages.length === 0 && !chat.snapshot.isStreaming}
      <p class="muted chat-empty">{emptyHint}</p>
    {/if}

    {#each visibleMessages as message, i (message.id ?? i)}
      <div class="bubble {message.role}" data-testid="{testid}-bubble-{message.role}">
        {message.content}
      </div>
    {/each}

    <!-- Live streaming text, before it lands as a persisted message. -->
    {#if chat.snapshot.isStreaming && chat.snapshot.streamingText}
      <div class="bubble assistant streaming">
        {chat.snapshot.streamingText}
      </div>
    {/if}

    <!-- Tool calls in flight: 🔧 name + spinner, then ✓/✗. -->
    {#if chat.snapshot.activeToolCalls.length > 0}
      <div class="tool-calls">
        {#each chat.snapshot.activeToolCalls as tool (tool.id)}
          <span class="tool-badge {tool.status}">
            🔧 {tool.functionName}
            {#if tool.status === 'running'}
              <span class="spinner"></span>
            {:else if tool.status === 'completed'}
              ✓
            {:else}
              ✗
            {/if}
          </span>
        {/each}
      </div>
    {/if}

    {#if thinking}
      <div class="bubble assistant thinking">thinking…</div>
    {/if}
  </div>

  {#if chat.snapshot.error}
    <p class="error-banner" role="alert">{chat.snapshot.error}</p>
  {/if}

  <div class="chat-input">
    <input
      type="text"
      {placeholder}
      data-testid="{testid}-input"
      bind:value={input}
      onkeydown={onKeydown}
      disabled={!chat.ready || chat.snapshot.isStreaming}
    />
    <button
      data-testid="{testid}-send"
      onclick={send}
      disabled={!chat.ready || chat.snapshot.isStreaming || !input.trim()}
    >
      Send
    </button>
  </div>
</section>
